# Generated by Django 3.2.9 on 2023-05-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apps/images/product', verbose_name='Фотография')),
                ('discounts', models.CharField(blank=True, max_length=16, null=True, verbose_name='Скидки')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('data', models.DateField(verbose_name='Дата')),
                ('price', models.CharField(max_length=16, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория')),
                ('partners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
    ]
