# Generated by Django 3.2.9 on 2023-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_playbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbill',
            name='image',
            field=models.ImageField(upload_to='apps/images/playbill', verbose_name='Фотография *385x165'),
        ),
    ]
