# Generated by Django 3.2.9 on 2023-06-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_size',
            field=models.CharField(default=1, max_length=16, verbose_name='Цена со скидкой'),
            preserve_default=False,
        ),
    ]
