# Generated by Django 3.2.9 on 2023-05-19 06:28

import apps.partners.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to=apps.partners.services.get_upload_path, validators=[apps.partners.services.validate_file_extension], verbose_name='Загрузить логотип *(150x150)')),
                ('mail', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование (брендовое название )')),
                ('address', models.CharField(max_length=64, verbose_name='Адрес компании')),
                ('org', models.CharField(blank=True, max_length=64, null=True, verbose_name='Организационная праовая форма')),
                ('inn', models.CharField(blank=True, max_length=16, null=True, verbose_name='ИНН')),
                ('activity_type', models.CharField(max_length=64, verbose_name='Тип деятельности')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('phone_one', models.CharField(blank=True, max_length=32, null=True, verbose_name='Номера телефонов')),
                ('phone_two', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('phone_three', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('phone_four', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('day', models.CharField(blank=True, choices=[['Понедельник', 'Понедельник'], ['Вторник', 'Вторник'], ['Среда', 'Среда'], ['Четверг', 'Четверг'], ['Пятница', 'Пятница'], ['Суббота', 'Суббота'], ['Воскресенье', 'Воскресенье']], default=None, max_length=16, null=True, verbose_name='Режим работы')),
                ('data_time', models.DateTimeField(blank=True, null=True, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'ПАРТНЁРА',
                'verbose_name_plural': 'ПАРТНЁРЫ',
                'db_table': 'partners',
            },
        ),
    ]
