# Generated by Django 3.2.9 on 2023-06-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20230607_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email_e',
            field=models.EmailField(default=1, max_length=64, verbose_name='Почта 2'),
            preserve_default=False,
        ),
    ]
