# Generated by Django 3.2.9 on 2023-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contacts_email_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email_r',
            field=models.EmailField(default=1, max_length=64, verbose_name='Почта 3'),
            preserve_default=False,
        ),
    ]
