# Generated by Django 3.2.9 on 2023-06-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contacts_email_ww'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email_e',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email_r',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email_ww',
        ),
    ]
