# Generated by Django 3.2.9 on 2023-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bankcard_mycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycard',
            name='name',
            field=models.CharField(max_length=32, verbose_name='№ карты'),
        ),
    ]
