# Generated by Django 3.2.9 on 2023-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_like_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='numcard',
            field=models.CharField(max_length=64, verbose_name='Номер карты'),
        ),
    ]
