# Generated by Django 3.2.9 on 2023-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_bankcard_numcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='code',
            field=models.BooleanField(max_length=12, verbose_name='Код CVC/CVV'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='period',
            field=models.BooleanField(max_length=12, verbose_name='Срок действия карты'),
        ),
    ]
