# Generated by Django 3.2.9 on 2023-06-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230612_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'verbose_name': 'Мои комментарии', 'verbose_name_plural': 'Мои комментарии'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Ваши понравившееся публикации', 'verbose_name_plural': 'Ваши понравившееся публикации'},
        ),
        migrations.AlterModelOptions(
            name='mycard',
            options={'verbose_name': 'Моя карта', 'verbose_name_plural': 'Моя карта'},
        ),
        migrations.AlterModelOptions(
            name='subscr',
            options={'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
