# Generated by Django 3.2.9 on 2023-06-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Oбратная связь',
                'verbose_name_plural': 'Oбратная связь',
            },
        ),
    ]
